### ISSUE TITLE
WARNING  Add-on config 'devices' use a deprecated format, the new format uses a list of paths only.

### ISSUE THREAD

**Issue by trynqz** [marciogranzotto/addon-transmission-nas#5]
21-02-23 16:48:40 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Transmission NAS
21-02-23 16:48:40 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Transmission NAS

Transmission NAS log, Protection mode is disabled. This warning appeared after last HA update.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Transmission NAS
 The torrent client for Home Assistant with OpenVPN and Samba Share support
-----------------------------------------------------------
 Add-on version: 1.0.0
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 5.12  (aarch64 / raspberrypi4-64)
 Home Assistant version: 2021.2.3
 Supervisor version: 2021.02.11
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to WARNING
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-transmission-configuration.sh: executing... 
[cont-init.d] 20-transmission-configuration.sh: exited 0.
[cont-init.d] 21-openvpn-configuration.sh: executing... 
[cont-init.d] 21-openvpn-configuration.sh: exited 0.
[cont-init.d] 30-nginx.sh: executing... 
[cont-init.d] 30-nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
mount: mounting //10.0.0.xxx/xxx/xxx/ on ///10.0.0.xxx/xxx/xxx/ failed: Permission denied
WARNING: Protection mode is ON. Unable to mount external drivers!
[2021-02-23 18:12:32.676] Transmission 2.94 (d8e60ee44f) started (session.c:740)

**Comment by marciogranzotto** [comment]
Should be fixed on v1.1.0
